# Generated by Django 6.0.2 on 2026-03-09 01:43

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entradagratitud',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradagratitud',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='entradas/'),
        ),
        migrations.AlterField(
            model_name='entradagratitud',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
