# Generated by Django 6.0.2 on 2026-03-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_entradagratitud_autor_entradagratitud_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='entradagratitud',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
